### ISSUE TITLE
Can't resolve 'prismjs/components/prism-jade'

### ISSUE THREAD

**Issue by Cydiater** [ChouUn/react-markdown-plus#2]
Hi, I just find that I can not get the component compiled.

```bash
./node_modules/react-markdown-plus/node_modules/prismjs-polyfill/lib/prism.js
Module not found: Can't resolve 'prismjs/components/prism-jade' in '/path/to/my/project/node_modules/react-markdown-plus/node_modules/prismjs-polyfill/lib'
```
I don't understand what happened, could you please give me some tips? Thank you very much!

**Comment by Ray-D-Song** [comment]
I encountered the same problem as you.
The solution is to create a new 'prism-jade.js' file in the 'node_modules/react-markdown-plus/node_modules/prismjs-polyfill/lib'.
You don't have to write any code in it, just create a new file to solve the problem.
Hope that solves your problem :)

**Comment by Cydiater** [comment]
> I encountered the same problem as you.
> The solution is to create a new 'prism-jade.js' file in the 'node_modules/react-markdown-plus/node_modules/prismjs-polyfill/lib'.
> You don't have to write any code in it, just create a new file to solve the problem.
> Hope that solves your problem :)

Thanks!
